version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db:rw
    ports:
      - "27017:27017"
  app:
    container_name: app-container
    image: node:20
    restart: always
    working_dir: /usr/app
    command: bash -c "npm install --omit=dev && npm run start"
    ports:
      - "5050:5050"
    volumes:
      - ./dist/:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    links:
      - mongo